Parameterize datasource images
hal/berg pull request #69
Opened 2023-06-19 08:53 UTC by spriadka

This PR adds support to configure datasource images to be used by the test suite via environment variables.

2023-06-19 08:57 UTC, spriadka commented
The CI check is failing due to the linting errors (to be fixed in https://github.com/hal/berg/pull/68).

2023-06-21 06:52 UTC, OndrejKotek requested changes

2023-06-21 09:52 UTC, OndrejKotek commented
Squash and rebase please

2023-06-21 10:22 UTC, spriadka commented
@OndrejKotek squashed and rebased 🙂

2023-06-21 10:49 UTC, OndrejKotek approved these changes

2023-06-21 12:21 UTC, merged